using System;
using System.Numerics;
using BLS.ElipticCurve.Interfaces;
using BLS.Fields.Implementations;

namespace BLS.ElipticCurve.Implementations
{
    /// <summary>
    /// Finds a point Q of order r in E[r] over the extension field F_{q^k}
    /// such that Q is not in the subgroup generated by P (a point over the base field).
    /// Uses the algorithm from "Finding a point in E[r]" paper.
    /// </summary>
    public static class TorsionPointFinder
    {
        /// <summary>
        /// Finds a point Q ∈ E[r] over F_{q^k} that is linearly independent from P.
        /// Algorithm: Q = π(S) - S, where S = (N_k/r²)*T for random T, and π is Frobenius endomorphism.
        /// MODIFIED: Using cofactor = N_k/r² instead of N_k/r for better success probability.
        /// </summary>
        /// <param name="curve">Elliptic curve over extension field F_{q^k}</param>
        /// <param name="r">Prime order (the largest prime divisor of the base field curve's group order)</param>
        /// <param name="maxAttempts">Maximum number of random point attempts (default 100)</param>
        /// <returns>Point Q ∈ E[r] such that Q ∉ ⟨P⟩</returns>
        public static IECPoint<ExtensionFieldElement> FindIndependentTorsionPoint(
            IEllipticCurve<ExtensionFieldElement> curve,
            BigInteger r,
            int maxAttempts = 100)
        {
            ArgumentNullException.ThrowIfNull(curve);
            if (r <= 1)
            {
                throw new ArgumentException("Order r must be a prime > 1", nameof(r));
            }

            var extensionField = curve.A.Field as ExtensionField;
            if (extensionField == null)
            {
                throw new ArgumentException("Curve must be defined over an ExtensionField", nameof(curve));
            }

            BigInteger q = extensionField.BaseField.Characteristic;
            int k = extensionField.ExtensionDegree;

            // Get N_k = #E(F_{q^k}) from the curve
            BigInteger N_k = curve.GroupOrder;

            // Verify r divides N_k
            if (N_k % r != 0)
            {
                throw new ArgumentException($"Order r={r} does not divide the curve group order N_k={N_k}", nameof(r));
            }

            // Use N_k/r² instead of N_k/r for better probability of finding non-infinity points !! 
            BigInteger cofactor = N_k / (r * r);
            var random = new Random(Guid.NewGuid().GetHashCode());

            for (int attempt = 0; attempt < maxAttempts; attempt++)
            {
                // Step 4: Choose a random point T \in E(F_{q^k}) and compute S = (N_k/r^2)*T
                var T = GenerateRandomPoint(curve, extensionField, random, maxAttempts: 1000);
                var S = T.Multiply(cofactor);

                if (S.IsInfinity)
                {
                    continue;
                }

                // Step 5: Apply Frobenius endomorphism: Q = \pi(S) - S
                var piS = ApplyFrobeniusEndomorphism(S, q, extensionField);
                var Q = piS.Add(S.Negate());

                // Verify Q ≠ O (which would mean S \in E(F_q), i.e., S is rational)
                if (!Q.IsInfinity)
                {
                    return Q;
                }
            }

            throw new InvalidOperationException($"Failed to find independent torsion point after {maxAttempts} attempts. This is statistically unlikely (p < (1/r)^{maxAttempts}).");
        }

        private static IECPoint<ExtensionFieldElement> GenerateRandomPoint(IEllipticCurve<ExtensionFieldElement> curve,ExtensionField field, Random random, int maxAttempts)
        {
            BigInteger q = field.BaseField.Characteristic;
            int k = field.ExtensionDegree;

            for (int attempt = 0; attempt < maxAttempts; attempt++)
            {
                // Generate random coefficients for x polynomial
                var coeffs = new BigInteger[k];
                for (int i = 0; i < k; i++)
                {
                    coeffs[i] = RandomBigInteger(random, q);
                }

                var randomPoly = new Polynomial(q, coeffs);
                var x = new ExtensionFieldElement(field, randomPoly);
                var rhs = x.Power(3).Add(curve.A.Multiply(x)).Add(curve.B);

                // For fields up to reasonable size, try all possible y values
                BigInteger fieldSize = BigInteger.Pow(q, k);
                if (fieldSize < 50000)
                {
                    // Brute force search for y (works for q² ≤ 50k, e.g., q ≤ 223)
                    for (BigInteger yi = 0; yi < fieldSize; yi++)
                    {
                        var yCoeffs = new BigInteger[k];
                        BigInteger temp = yi;
                        for (int j = 0; j < k; j++)
                        {
                            yCoeffs[j] = temp % q;
                            temp /= q;
                        }

                        var yPoly = new Polynomial(q, yCoeffs);
                        var y = new ExtensionFieldElement(field, yPoly);
                        var lhs = y.Multiply(y);

                        if (lhs.Equals(rhs))
                        {
                            var point = curve.CreatePoint(x, y);
                            if (curve.IsOnCurve(point) && !point.IsInfinity)
                            {
                                return point;
                            }
                        }
                    }
                }
                else
                {
                    // Use square root formula for larger fields
                    var y = TrySolveForY(rhs, field);
                    if (y != null)
                    {
                        var point = curve.CreatePoint(x, y);
                        if (curve.IsOnCurve(point) && !point.IsInfinity)
                        {
                            return point;
                        }
                    }
                }
            }

            throw new InvalidOperationException("Failed to generate a random point on the curve.");
        }

        /// <summary>
        /// Attempts to find y such that y² = rhs in the extension field.
        /// For fields where q^k ≡ 3 (mod 4), we can use y = rhs^((q^k+1)/4).
        /// </summary>
        private static ExtensionFieldElement? TrySolveForY(ExtensionFieldElement rhs, ExtensionField field)
        {
            BigInteger q = field.BaseField.Characteristic;
            int k = field.ExtensionDegree;
            BigInteger qk = BigInteger.Pow(q, k);

            // Check if q^k ≡ 3 (mod 4)
            if (qk % 4 == 3)
            {
                // Compute y = rhs^((q^k+1)/4)
                BigInteger exponent = (qk + 1) / 4;
                var y = rhs.Power(exponent);

                // Verify y² = rhs
                var ySquared = y.Multiply(y);
                if (ySquared.Equals(rhs))
                {
                    return y;
                }
            }

            // For other cases, we'd need Tonelli-Shanks or other methods
            // For now, return null
            return null;
        }

        /// <summary>
        /// Applies the Frobenius endomorphism π to a point (x, y) on the elliptic curve.
        /// π(x, y) = (x^q, y^q) where q is the base field characteristic.
        /// </summary>
        private static IECPoint<ExtensionFieldElement> ApplyFrobeniusEndomorphism(
            IECPoint<ExtensionFieldElement> point,
            BigInteger q,
            ExtensionField field)
        {
            if (point.IsInfinity)
            {
                return point;
            }

            // π(x, y) = (x^q, y^q)
            var xPowQ = point.X.Power(q);
            var yPowQ = point.Y.Power(q);

            return point.Curve.CreatePoint(xPowQ, yPowQ);
        }

        /// <summary>
        /// Generates a random BigInteger in the range [0, max).
        /// </summary>
        private static BigInteger RandomBigInteger(Random random, BigInteger max)
        {
            if (max <= int.MaxValue)
            {
                return random.Next((int)max);
            }

            // For larger values, generate random bytes
            byte[] bytes = max.ToByteArray();
            BigInteger result;
            do
            {
                random.NextBytes(bytes);
                bytes[bytes.Length - 1] &= 0x7F; // Ensure positive
                result = new BigInteger(bytes);
            } while (result >= max);

            return result;
        }
    }
}
