using System;
using System.Numerics;
using BLS.ElipticCurve.Interfaces;
using BLS.Fields.Implementations;

namespace BLS.ElipticCurve.Implementations
{
    /// <summary>
    /// Finds a point Q of order r in E[r] over the extension field F_{q^k}
    /// such that Q is not in the subgroup generated by P (a point over the base field).
    /// Uses the algorithm from "Finding a point in E[r]" paper.
    /// </summary>
    public static class TorsionPointFinder
    {
        /// <summary>
        /// Finds a point Q ∈ E[r] over F_{q^k} that is linearly independent from P.
        /// Algorithm: Q = π(S) - S, where S = cofactor*T for random T, and π is Frobenius endomorphism.
        /// The cofactor is N_k with all factors of r removed, ensuring it is coprime to r
        /// so that multiplication preserves the non-rational eigenspace of Frobenius.
        /// </summary>
        /// <param name="curve">Elliptic curve over extension field F_{q^k}</param>
        /// <param name="r">Prime order (the largest prime divisor of the base field curve's group order)</param>
        /// <param name="maxAttempts">Maximum number of random point attempts (default 100)</param>
        /// <returns>Point Q ∈ E[r] such that Q ∉ ⟨P⟩</returns>
        public static IECPoint<ExtensionFieldElement> FindIndependentTorsionPoint(
            IEllipticCurve<ExtensionFieldElement> curve,
            BigInteger r,
            int maxAttempts = 100)
        {
            ArgumentNullException.ThrowIfNull(curve);
            if (r <= 1)
            {
                throw new ArgumentException("Order r must be a prime > 1", nameof(r));
            }

            var extensionField = curve.A.Field as ExtensionField;
            if (extensionField == null)
            {
                throw new ArgumentException("Curve must be defined over an ExtensionField", nameof(curve));
            }

            BigInteger q = extensionField.BaseField.Characteristic;
            int k = extensionField.ExtensionDegree;

            // Get N_k = #E(F_{q^k}) from the curve
            BigInteger N_k = curve.GroupOrder;

            // Verify r divides N_k
            if (N_k % r != 0)
            {
                throw new ArgumentException($"Order r={r} does not divide the curve group order N_k={N_k}", nameof(r));
            }

            // Strip all factors of r from N_k so the cofactor is coprime to r.
            // This preserves the full r-primary part (including the non-rational eigenspace)
            // when computing S = cofactor * T.
            BigInteger cofactor = N_k;
            while (cofactor % r == 0)
                cofactor /= r;
            var random = new Random(Guid.NewGuid().GetHashCode());

            for (int attempt = 0; attempt < maxAttempts; attempt++)
            {
                // Choose a random point T ∈ E(F_{q^k}) and project onto the r-primary part
                var T = GenerateRandomPoint(curve, extensionField, random, maxAttempts: 1000);
                var S = T.Multiply(cofactor);

                if (S.IsInfinity)
                {
                    continue;
                }

                // Step 5: Apply Frobenius endomorphism: Q = \pi(S) - S
                var piS = ApplyFrobeniusEndomorphism(S, q, extensionField);
                var Q = piS.Add(S.Negate());

                if (Q.IsInfinity)
                {
                    continue;
                }

                // Reduce Q into E[r]: since cofactor is coprime to r, Q lives in E[r^e].
                // Repeatedly multiply by r until r*Q = O.
                var rQ = Q.Multiply(r);
                while (!rQ.IsInfinity)
                {
                    Q = rQ;
                    rQ = Q.Multiply(r);
                }

                if (!Q.IsInfinity)
                {
                    return Q;
                }
            }

            throw new InvalidOperationException($"Failed to find independent torsion point after {maxAttempts} attempts. This is statistically unlikely (p < (1/r)^{maxAttempts}).");
        }

        private static IECPoint<ExtensionFieldElement> GenerateRandomPoint(
            IEllipticCurve<ExtensionFieldElement> curve, 
            ExtensionField field, 
            Random random, 
            int maxAttempts)
        {
            BigInteger q = field.BaseField.Characteristic;
            int k = field.ExtensionDegree;

            for (int attempt = 0; attempt < maxAttempts; attempt++)
            {
                // Generate random coefficients for x polynomial
                var coeffs = new BigInteger[k];
                for (int i = 0; i < k; i++)
                {
                    coeffs[i] = NumberTheoryUtils.RandomBigInteger(random, q);
                }

                var randomPoly = new Polynomial(q, coeffs);
                var x = new ExtensionFieldElement(field, randomPoly);
                var rhs = x.Power(3).Add(curve.A.Multiply(x)).Add(curve.B);

                // Use Tonelli-Shanks from NumberTheoryUtils to find square root in extension field
                var y = NumberTheoryUtils.SqrtModExtensionField(rhs, field, random);
                if (y != null)
                {
                    var point = curve.CreatePoint(x, y);
                    if (curve.IsOnCurve(point) && !point.IsInfinity)
                    {
                        return point;
                    }
                }
            }

            throw new InvalidOperationException("Failed to generate a random point on the curve.");
        }

        /// <summary>
        /// Applies the Frobenius endomorphism π to a point (x, y) on the elliptic curve.
        /// π(x, y) = (x^q, y^q) where q is the base field characteristic.
        /// </summary>
        private static IECPoint<ExtensionFieldElement> ApplyFrobeniusEndomorphism(
            IECPoint<ExtensionFieldElement> point,
            BigInteger q,
            ExtensionField field)
        {
            if (point.IsInfinity)
            {
                return point;
            }

            // π(x, y) = (x^q, y^q)
            var xPowQ = point.X.Power(q);
            var yPowQ = point.Y.Power(q);

            return point.Curve.CreatePoint(xPowQ, yPowQ);
        }
    }
}
